### ISSUE TITLE
^_^

### ISSUE THREAD

**Issue by SuJiKiNen** [Youka/SSBRenderer#1]
here are some my wishes:
1,animation work for position which can control by formula.
2,mulitple formula in one animation,contorl by uncross time.
3,ruby tag 
4,the difference between ssb and ass make it a little unconvient to create effect by auto4 or nyufx.

**Comment by Youka** [comment]
1) Using animation progress control formulas for positions is already possible. See the "effects.ssb" example, with a combination of animated 'position' and/or (one or more) 'translate' you can make curve movements amongst others.

2) Multiple animations make more sense, one formula can already express everything what's needed for one group of style tags.

3) Put on local todo list.

4) List what you don't like and i put it to my plans for the future format change.
(Btw.: Aegisub gets LuaJIT in next releases, so maybe i write a new karaskel with SSB support or NyuFX2 for SSB.)

**Comment by SuJiKiNen** [comment]
1) sorry,I didn't test it very well.does it only work for trignometry?  if  there is a way to make biezier curve it would be better.

3) I will be waiting for it.^_^

4)temporarily,is style setting,it has to mannul to change it,you know,position caculations are based on style,if aegisub could change for it,it would be fine.if style settings are same,auto4 karaoke scritpts would be easy transform  or modify to ssb way,moreover,tags are quite long to ass tags,so I think a autocomplete tool integrate with with aegisub could be necessary.^_^waitng for the LuaJIT release. 

5)Add more path command to make it same with SVG path,so it would easily to create vector draw by some other good tools.

6)multiple border,something like border1,border2,border3.not a good idea,I think

7)gif texture support.

(Btw,about LVS,is there any  better way to keep variable value which something caculateed in pre-frames except  files.)
